### ISSUE TITLE
Clarification of terms of use regarding creation of derivative works

### ISSUE THREAD

**Issue by fedorov** [som-shahlab/INSPECT_public#1]
I followed the link to the "Stanford AIMI" link with the dataset https://stanfordaimi.azurewebsites.net/datasets/521d0d11-7c3c-45ef-8b99-a49cd70cba2c, and reading the license agreement I found this statement among other terms of use: "You must not modify, reverse engineer, decompile, or create derivative works from the INSPECT: A Multimodal Dataset for Pulmonary Embolism Diagnosis and Prognosis Dataset."

What is the definition of "derivative works"? Aren't model weights, or any artifact generated by the code that uses the dataset an instance of "derivative works"? How about publications that use the dataset?

It would be helpful if the definition of "derivative works" could be provided as part of the repository documentation.

**Comment by ZepengHuo** [comment]
Thanks for the question!

We are still finalizing our licence with our Privacy Office, with the hope that our dataset can be open freely to the community to build their own models/papers.
