### ISSUE TITLE
Availability of the full dataset

### ISSUE THREAD

**Issue by yayapa** [som-shahlab/INSPECT_public#2]
Thank you for your excellent work. I found the data on request at the [website](https://stanfordaimi.azurewebsites.net). However, the data seems to be too small (26.69 GB) for the 19,402 patients, and after downloading this dataset, I checked the CSV files. For example, _emr/many_examples_1.csv_ contains only 100 unique _patient\_id_ s and  _/metadata/dicom_headers.csv_  only 122 _PatientID_ s . Therefore, I would like to ask:

1. Do I understand correctly that the data is now available only for 100 patients under this link?
2. Are you planning to publish the full dataset for 19,409 patients? If so, is there any approximate release date for the publishing? Or can the data be requested for research purposes in the near future?

**Comment by yayapa** [comment]
Thank you very much!

**Comment by VividLe** [comment]
Thank you for your great efforts on the ISPECT dataset. Is there any update about the release of the full dataset?

**Comment by ZepengHuo** [comment]
The PHI review team is trying their best and we should finish that soon. Thanks for your patience!
