### ISSUE TITLE
inconsistent ids for images and reports

### ISSUE THREAD

**Issue by JINGEWU** [som-shahlab/INSPECT_public#3]
Hi I download the data you provided from https://stanfordaimi.azurewebsites.net/datasets/521d0d11-7c3c-45ef-8b99-a49cd70cba2c
It contains ~130 patient reports (impressions) with CT scans. And it seems the images ids and the patient ids are not matched. Could you provide more detail on how to match the images and report?

**Comment by tim-the-baker** [comment]
@ZepengHuo Any word on approximately how much longer the data privacy review will take? Even having access to a small sample of the complete dataset will be helpful.

**Comment by ZepengHuo** [comment]
@tim-the-baker hello, we just received approval from Secondary Data Use Committee. The final stretch is to settle down on DUA. Probably within a moth

**Comment by tim-the-baker** [comment]
@ZepengHuo Thank you for the update! I look forward to it.
